# Generated by Django 4.0.1 on 2022-01-07 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_link", models.URLField(unique=True)),
                (
                    "short_link",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="links", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
