# Generated by Django 4.0.1 on 2022-01-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("short_link", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="links",
            options={
                "ordering": ["-id"],
                "verbose_name": "link",
                "verbose_name_plural": "links",
            },
        ),
    ]
